// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Product.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Contracts {
  public static partial class ProductService
  {
    static readonly string __ServiceName = "google.protobuf.ProductService";

    static readonly grpc::Marshaller<global::Contracts.GetProductsForCustomerRequest> __Marshaller_google_protobuf_GetProductsForCustomerRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.GetProductsForCustomerRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Contracts.GetProductsForCustomerResponse> __Marshaller_google_protobuf_GetProductsForCustomerResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.GetProductsForCustomerResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Contracts.GetProductsForCustomerRequest, global::Contracts.GetProductsForCustomerResponse> __Method_GetProductForCustomer = new grpc::Method<global::Contracts.GetProductsForCustomerRequest, global::Contracts.GetProductsForCustomerResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetProductForCustomer",
        __Marshaller_google_protobuf_GetProductsForCustomerRequest,
        __Marshaller_google_protobuf_GetProductsForCustomerResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Contracts.ProductReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ProductService</summary>
    public abstract partial class ProductServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Contracts.GetProductsForCustomerResponse> GetProductForCustomer(global::Contracts.GetProductsForCustomerRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ProductService</summary>
    public partial class ProductServiceClient : grpc::ClientBase<ProductServiceClient>
    {
      /// <summary>Creates a new client for ProductService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ProductServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ProductService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ProductServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ProductServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ProductServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Contracts.GetProductsForCustomerResponse GetProductForCustomer(global::Contracts.GetProductsForCustomerRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetProductForCustomer(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Contracts.GetProductsForCustomerResponse GetProductForCustomer(global::Contracts.GetProductsForCustomerRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetProductForCustomer, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Contracts.GetProductsForCustomerResponse> GetProductForCustomerAsync(global::Contracts.GetProductsForCustomerRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetProductForCustomerAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Contracts.GetProductsForCustomerResponse> GetProductForCustomerAsync(global::Contracts.GetProductsForCustomerRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetProductForCustomer, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ProductServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ProductServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ProductServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetProductForCustomer, serviceImpl.GetProductForCustomer).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ProductServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetProductForCustomer, serviceImpl.GetProductForCustomer);
    }

  }
}
#endregion
